services:
  # A Django web service
  - type: web
    name: django-template-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py
    startCommand: gunicorn sample_website.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-template-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: EMAIL_BACKEND
        value: sample_website.mailersend_backend.MailerSendBackend
      - key: MAILERSEND_API_KEY
        sync: false  # This needs to be set manually in the Render dashboard
      - key: DEFAULT_FROM_EMAIL
        sync: false  # This needs to be set manually in the Render dashboard (ex: noreply@django-template-app.com with valid mailersend doamin)

# Free plan only allows 1 database
# if user already has a database, use it in config above and comment out the block below
databases:
  - name: django-template-app-db
    plan: free
    databaseName: django_template_app
    user: django_template_app